apiVersion: v1
data:
  dbhost: svc-mysql-test-02.default
  dbport: "3306"
  all_databases: "true"
kind: ConfigMap
metadata:
  name: config-mysqldump
  namespace: mysql-bak
---
apiVersion: v1
data:
  dbuser: YmFrX2R1bXA=
  dbpass: QmFrLjRkdW1w
kind: Secret
metadata:
  name: srt-mysqldump
  namespace: mysql-bak
type: Opaque
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-mysqldump
  namespace: mysql-bak
spec:
  schedule: 30 2 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqldump
            image: harbor.cloudminds.com/mysql/mysqldump:1.1.2
            env:
              - name: ALL_DATABASES
                valueFrom:
                  configMapKeyRef:
                    name: config-mysqldump
                    key: all_databases
              - name: DB_HOST
                valueFrom:
                  configMapKeyRef:
                    name: config-mysqldump
                    key: dbhost
              - name: DB_PORT
                valueFrom:
                  configMapKeyRef:
                    name: config-mysqldump
                    key: dbport
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: srt-mysqldump
                    key: dbuser
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: srt-mysqldump
                    key: dbpass
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: /mysqldump
                name: mysqldump
          volumes:
            - name: mysqldump
              persistentVolumeClaim:
                claimName: pvc-mysql-bak
          restartPolicy: OnFailure
